Added admin stats page
Xon/XenForo2-RedisCache pull request #1
Opened 2018-02-02 18:23 UTC by yugensoft

Let me know if this covers what you needed

2018-02-02 23:39 UTC, Xon commented
Can you inject the redis stats onto the home page above the Logged activity section? The styling will need changing to fit.

The redis info accessible via version is fairly hard to read, I think the css needs looking at;
![image](https://user-images.githubusercontent.com/635541/35759443-ad5527f2-08b4-11e8-9c3e-0915e346e864.png)

The slave info doesn't open in an overlay either (OverlayTrigger is an XF1 class name)

2018-02-02 23:43 UTC, Xon requested changes

2018-02-02 23:43 UTC, Xon commented on upload/src/addons/SV/RedisCache/_output/templates/admin/SV_Redis_info.html
> +    <div class="secondaryContent statsList">
This css needs porting to XF2 equivalents

2018-02-02 23:43 UTC, Xon commented on upload/src/addons/SV/RedisCache/_output/templates/admin/SV_Redis_info_Wrapper.html
> +<div class="splash">
This wrapper class was used in XF2 to make the overlap popup work compared to the injected inline version.

2018-02-03 06:09 UTC, yugensoft commented
Alright I believe that covers it

2018-02-03 08:31 UTC, merged

2018-02-03 08:31 UTC, Xon commented
LGTM